/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.poo2.gui;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import ufps.poo2.gui.controller.Controlador;

/**
 *
 * @author YHUVER
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    private Controlador myC;
    private PanelJuego myJ;
    private PanelInicio myI;
    private PanelUsuario myU;
    private Historial myH;
    private int tablero;
    
    public Frame() {
        initComponents();
        myC=new Controlador(this);
        tablero=0;
        miInicioActionPerformed(null);
    }

    public Controlador getMyC() {
        return myC;
    }

    public void setMyC(Controlador myC) {
        this.myC = myC;
    }

    public PanelJuego getMyJ() {
        return myJ;
    }

    public void setMyJ(PanelJuego myJ) {
        this.myJ = myJ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miInicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miUsuario1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("INICIO");

        miInicio.setText("Inicio");
        miInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInicioActionPerformed(evt);
            }
        });
        jMenu1.add(miInicio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("REGISTRAR");

        miUsuario.setText("Usuario");
        miUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuario);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ARCHIVOS");

        miUsuario1.setText("CHAT");
        miUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuario1ActionPerformed(evt);
            }
        });
        jMenu3.add(miUsuario1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void miUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioActionPerformed
        // TODO add your handling code here:
        remover();
        myU=new PanelUsuario(this);
        getContentPane().add(myU);
        pack();
    }//GEN-LAST:event_miUsuarioActionPerformed

    private void miInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInicioActionPerformed
        // TODO add your handling code here:
        remover();
        myI= new PanelInicio();
        getContentPane().add(myI);
        pack();
        
    }//GEN-LAST:event_miInicioActionPerformed

    private void miUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuario1ActionPerformed
        // TODO add your handling code here:
        remover();
        myH=new Historial(this);
        getContentPane().add(myH);
        pack();
    }//GEN-LAST:event_miUsuario1ActionPerformed

    public int getTablero() {
        return tablero;
    }

    public void setTablero(int tablero) {
        this.tablero = tablero;
    }
public void generarJuego(int tab){
    remover();
        myJ=new PanelJuego(this, tab);
        getContentPane().add(myJ);
        pack();
}
    
    public void remover(){
        if(myI!=null){
            remove(myI);
        }
        if(myJ!=null){
            remove(myJ);
        }
        if(myU!=null){
            remove(myU);
        }
        if(myH!=null){
            remove(myH);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miInicio;
    private javax.swing.JMenuItem miUsuario;
    private javax.swing.JMenuItem miUsuario1;
    // End of variables declaration//GEN-END:variables
}
