/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.poo2.gui;

import java.net.InetAddress;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ufps.poo2.hilo.HiloJugador;
//import ufps.poo2.gui.controller.Controlador;


/**
 *
 * @author Admin
 */
public class PanelUsuario extends javax.swing.JPanel {

//    private Controlador myControlador;
private Frame myF;
private HiloJugador hilo;

    /**
     * Creates new form UsuarioPanel
     */
    public PanelUsuario(Frame myf) {
        initComponents();
        myF=myf;

        
        this.bloquearPanelServidor(false);
        this.bloquearPanelConectar(false);
        this.bloquearPanelCrear(false);
        this.txtArea.setText("No se han unido Jugadores");
        

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelConectar = new javax.swing.JPanel();
        lblDireccion = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        btnConectar = new javax.swing.JButton();
        cbConectar = new javax.swing.JCheckBox();
        lblDireccion3 = new javax.swing.JLabel();
        txtNombreJ = new javax.swing.JTextField();
        panelCrear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTablero = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbCrear = new javax.swing.JCheckBox();
        panelServidor = new javax.swing.JPanel();
        lblDireccion1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        cbCrearPartida = new javax.swing.JCheckBox();
        lblDireccion2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        jLabel6.setText("jLabel6");

        setBackground(new java.awt.Color(255, 255, 255));

        btnGuardar.setText("JUGAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("REGISTRAR USUARIO");

        panelConectar.setBackground(new java.awt.Color(255, 255, 255));

        lblDireccion.setText("DIRECCION IP SERVIDOR:");

        btnConectar.setText("CONECTAR");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        cbConectar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbConectar);
        cbConectar.setText("Conectarse a un juego");
        cbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConectarActionPerformed(evt);
            }
        });

        lblDireccion3.setText("NOMBRE JUGADOR:");

        javax.swing.GroupLayout panelConectarLayout = new javax.swing.GroupLayout(panelConectar);
        panelConectar.setLayout(panelConectarLayout);
        panelConectarLayout.setHorizontalGroup(
            panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConectarLayout.createSequentialGroup()
                .addGroup(panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConectarLayout.createSequentialGroup()
                        .addComponent(cbConectar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelConectarLayout.createSequentialGroup()
                        .addGroup(panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConectarLayout.createSequentialGroup()
                                .addComponent(lblDireccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(txtNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConectarLayout.createSequentialGroup()
                                .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnConectar)))
                .addContainerGap())
        );
        panelConectarLayout.setVerticalGroup(
            panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConectarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbConectar)
                .addGroup(panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConectarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion)
                            .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion3)))
                    .addGroup(panelConectarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnConectar)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        panelCrear.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("TABLERO");

        cmbTablero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5X5", "6X6", "7X7", "8X8", "9X9", "10X10", "11X11", "12X12", "13X13", "14X14", "15X15", "16X16" }));
        cmbTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTableroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cmbTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel5.setText("Seleccione una opción para jugar...");

        cbCrear.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbCrear);
        cbCrear.setText("Escoja Tablero");
        cbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCrearActionPerformed(evt);
            }
        });

        panelServidor.setBackground(new java.awt.Color(255, 255, 255));

        lblDireccion1.setText("Nombre Del Creador");

        btnCrear.setText("CREAR PARTIDA");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        cbCrearPartida.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbCrearPartida);
        cbCrearPartida.setText("Crear una Partida");
        cbCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCrearPartidaActionPerformed(evt);
            }
        });

        lblDireccion2.setText("Lista De Jugadores Enlazados: ");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout panelServidorLayout = new javax.swing.GroupLayout(panelServidor);
        panelServidor.setLayout(panelServidorLayout);
        panelServidorLayout.setHorizontalGroup(
            panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbCrearPartida)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelServidorLayout.createSequentialGroup()
                        .addComponent(lblDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelServidorLayout.setVerticalGroup(
            panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCrearPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDireccion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbCrear)
                                                .addComponent(panelConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(panelServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(panelConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(cbCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void mostrarJugadoresConectados(){
        hilo=new HiloJugador(this.txtArea, myF.getMyC());
        hilo.start();
    }
    private void detenerHilo(){
        hilo.detener();
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int tam=myF.getMyC().getTablero();
       
        if(tam==0){
            
        int tablero=Integer.parseInt(this.cmbTablero.getSelectedItem().toString().split("X")[0]);   
        this.myF.generarJuego(tablero);
        this.myF.getMyC().enviarTablero(tablero);
        this.myF.getMyC().enviarListaJugadores();
        }
        else{
            this.myF.generarJuego(tam);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:

        String nombre=this.txtNombreJ.getText();
        String ip=this.txtIP.getText();
        if(nombre.isEmpty()||ip.isEmpty()){
            JOptionPane.showMessageDialog(null, "llene los espacios por favor");
        }
        else{
            
        
            try {
                myF.getMyC().iniciarCliente(ip);
              String cad= myF.getMyC().enviarJugadores(nombre, ip);
               JOptionPane.showMessageDialog(null, cad);
               
            } catch (Exception ex) {
                Logger.getLogger(PanelUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnConectarActionPerformed

    private void cbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConectarActionPerformed
        // TODO add your handling code here:
        
        this.bloquearPanelConectar(true);
        this.bloquearPanelCrear(false);
        bloquearPanelServidor(false);
        
        this.limpiar();
    }//GEN-LAST:event_cbConectarActionPerformed

    private void cbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCrearActionPerformed
        // TODO add your handling code here:
        this.bloquearPanelConectar(false);
        this.bloquearPanelCrear(true);
        bloquearPanelServidor(false);
        this.limpiar();
    }//GEN-LAST:event_cbCrearActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        String nombre=this.txtNombre.getText();
        
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite los datos correspondientes");
        }
        else{
            
        
            try {
                this.txtArea.setText("");
                String cad=this.myF.getMyC().registrarJugador(nombre, InetAddress.getLocalHost().toString().split("/")[1]);
                JOptionPane.showMessageDialog(null,cad);
                
                mostrarJugadoresConectados();
                
                this.txtNombre.setText("");
                this.txtNombre.setEnabled(false);
                this.btnCrear.setEnabled(false);
                this.btnConectar.setEnabled(false);
                
            } catch (Exception ex) {
                Logger.getLogger(PanelUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cbCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCrearPartidaActionPerformed
        // TODO add your handling code here:
        this.bloquearPanelServidor(true);
        this.bloquearPanelConectar(false);
        this.bloquearPanelCrear(false);
        this.limpiar();
    }//GEN-LAST:event_cbCrearPartidaActionPerformed

    private void cmbTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTableroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTableroActionPerformed

    public void limpiar() {
        this.cmbTablero.setSelectedIndex(0);
        this.txtIP.setText("");

    }

    public void bloquearPanelConectar(boolean habilitar) {
        this.txtIP.setEnabled(habilitar);
        this.txtNombreJ.setEnabled(habilitar);

    }

    public void bloquearPanelCrear(boolean habilitar) {
        this.cmbTablero.setEnabled(habilitar);
    }
    
    public void bloquearPanelServidor(boolean habilitar){
        this.txtArea.setEnabled(habilitar);
        this.txtNombre.setEnabled(habilitar);
    }

    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbConectar;
    private javax.swing.JCheckBox cbCrear;
    private javax.swing.JCheckBox cbCrearPartida;
    private javax.swing.JComboBox cmbTablero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JLabel lblDireccion2;
    private javax.swing.JLabel lblDireccion3;
    private javax.swing.JPanel panelConectar;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelServidor;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreJ;
    // End of variables declaration//GEN-END:variables
}
